exclude: ['README.md', 'preview.sh', 'Gemfile', 'Gemfile.lock']

# Used to generate the site
title: "Talk Sporty To Me"
title_short: "TSTM"
email: "your-email@example.com"
description: "An absolute sport ignoramus engages aficionados in real ball talk"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bonengeber.ddns.net" # the base hostname & protocol for your site
itunes_url: "https://itunes.apple.com/us/podcast/xxx"

# itunes_id creates a smart banner on Safari in iOS prompting
# visitors to subscribe
# Uncomment next line to enable
#itunes_id: xxx # The ID is after the last slash in itunes_url above minus the letters "id"
twitter_username: yourtwitter
twitter_podcastname: yourpodcasttwitter

# For the SEO tag
seo:
  name: "Talk Sporty To Me"
  type: "CreativeWork"
  about: "An absolute sport ignoramus engages aficionados in real ball talk"
  person: "Clar"

# Used to generate the iTunes-compatible RSS feed
podcast:
  owner:
    name: Clar
    email: your-podcast-email@example.com
  explicit: "no" # Change to yes if you're a potty mouth
  image: /img/podart.webp # iTunes requires 2,000 pixel art
  keywords: "news"
  categories:
    - category: "Sports & Recreation"
    - category: "Society & Culture"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugins
plugins:
  - jekyll-seo-tag
